create table migration (
  migration_id integer primary key generated by default as identity,
  filename text not null,
  created_at timestamp with time zone default current_timestamp
);

create table user_account (
  user_account_id integer primary key generated by default as identity,
  first_name text not null,
  last_name text not null,
  email text not null
);
